# Generated by Django 2.2 on 2022-03-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='if_private',
            field=models.BooleanField(default=False),
        ),
    ]
