# Generated by Django 2.2 on 2022-03-08 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiseup', '0003_auto_20220309_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['date']},
        ),
    ]
