# Generated by Django 2.2 on 2022-03-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiseup', '0004_auto_20220309_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date']},
        ),
    ]
