# Generated by Django 2.2 on 2022-03-11 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiseup', '0007_auto_20220311_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-date']},
        ),
    ]
