# Generated by Django 2.2 on 2022-04-04 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiseup', '0008_auto_20220311_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
